<MyRoot>:
    random_label: random_label

    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Random Number"
            font_size: 64
            color:0.52, 0.18, 0.94
        Label:
            id: random_label
            text: "_"
            font_size: 64
        Button:
            text:"Generate"
            font_size: 32
            size:100, 50
            background_color:0.52, 0.18, 0.94
            on_press:root.generate_number()